[workspace]
resolver = "2"
members = ["programs/*", "client"]

[profile.test]
opt-level = 0

[profile.release]
lto = "fat"
codegen-units = 1
overflow-checks = true

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
