[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dex_solana = "Dc5FSiBDTHsDiz191WSMJQ694FesS3ngNkS5T4ubjLs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx --yes ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.test.ts'"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
faucet_port = 9901
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# ==================== Token Mints ====================
[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112"  # Wrapped SOL

[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"  # USDC

[[test.validator.clone]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"  # USDT

[[test.validator.clone]]
address = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"  # mSOL

# ==================== DEX Programs ====================
[[test.validator.clone]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"  # Raydium AMM V4

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"  # Token Program

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"  # Associated Token Program

# ==================== Raydium SOL-USDC Pool ====================
# Pool: 58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2
[[test.validator.clone]]
address = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"  # SOL-USDC Pool Account

[[test.validator.clone]]
address = "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1"  # AMM Authority

[[test.validator.clone]]
address = "HmiHHzq4Fym9e1D4qzLS6LDDM3tNsCTBPDWHTLZ763jY"  # AMM Open Orders

[[test.validator.clone]]
address = "CZza3Ej4Mc58MnxWA385itCC9jCo3L1D7zc3LKy1bZMR"  # AMM Target Orders

[[test.validator.clone]]
address = "DQyrAcCrDXQ7NeoqGgDCZwBvWDcYmFCjSb9JtteuvPpz"  # Pool Base Vault (SOL)

[[test.validator.clone]]
address = "HLmqeL62xR1QoZ1HKKbXRrdN1p3phKpxRMb2VVopvBBz"  # Pool Quote Vault (USDC)

# ==================== Serum Market ====================
[[test.validator.clone]]
address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"  # Serum DEX Program

[[test.validator.clone]]
address = "8BnEgHoWFysVcuFFX7QztDmzuH8r5ZFvyP3sYwn1XTh6"  # Serum Market (SOL-USDC)

[[test.validator.clone]]
address = "96RyJdJVeo5Yr5FjJRn6AaED89myiD9fjp2Fq3zccrfj"  # Serum Bids

[[test.validator.clone]]
address = "48cNXXS5fKsA3ufrYMHxqmV93L2449tu4Ng9mQS2Mxzt"  # Serum Asks

[[test.validator.clone]]
address = "5KKsLVU6TcbVDK4BS6K1DGDxnh4Q9xjYJ8XaDCG5t8ht"  # Serum Event Queue (SOL-USDC)

[[test.validator.clone]]
address = "FaFLrnxNpW4z6ivYvmDaoxvHXvi7G78veWcjW81siiE6"  # Serum Base Vault

[[test.validator.clone]]
address = "BmrxsPxDjYavNotwdYNMJm1Z3ruRY5AXTA7m85XZpSYj"  # Serum Quote Vault

# Note: Serum Vault Signer (V3gQJJhHGaRKS7uoeUVhMKzKWqbQ6dKofhPqGBxmg2c) is a PDA
# and cannot be cloned - it will be derived/created at runtime during swaps

# ==================== Additional Raydium Pools (Optional) ====================
# Uncomment these if you need more pools for testing

# [[test.validator.clone]]
# address = "AVs9TA4nWDzfPJE9gGVNJMVhcQy3V9PGazuz33BfG2RA"  # RAY-USDC Pool

# [[test.validator.clone]]
# address = "DVa7Qmb5ct9RCpaU7UTpSaf3GVMYz17vNVU67XpdCRut"  # SOL-USDT Pool
