[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dex_solana = "Dc5FSiBDTHsDiz191WSMJQ694FesS3ngNkS5T4ubjLs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx --yes ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.test.ts'"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
faucet_port = 9901
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

# ==================== Token Mints ====================
[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112"  # Wrapped SOL

[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"  # USDC

[[test.validator.clone]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"  # USDT

[[test.validator.clone]]
address = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So"  # mSOL

# ==================== DEX Programs ====================
[[test.validator.clone]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"  # Raydium AMM V4

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"  # Token Program

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"  # Associated Token Program

# ==================== Raydium SOL-USDC Pool ====================
# Pool: 58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2
[[test.validator.clone]]
address = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"  # SOL-USDC Pool Account

[[test.validator.clone]]
address = "5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1"  # AMM Authority

[[test.validator.clone]]
address = "HmiHHzq4Fym9e1D4qzLS6LDDM3tNsCTBPDWHTLZ763jY"  # AMM Open Orders

[[test.validator.clone]]
address = "CZza3Ej4Mc58MnxWA385itCC9jCo3L1D7zc3LKy1bZMR"  # AMM Target Orders

[[test.validator.clone]]
address = "DQyrAcCrDXQ7NeoqGgDCZwBvWDcYmFCjSb9JtteuvPpz"  # Pool Base Vault (SOL)

[[test.validator.clone]]
address = "HLmqeL62xR1QoZ1HKKbXRrdN1p3phKpxRMb2VVopvBBz"  # Pool Quote Vault (USDC)

# ==================== Serum Market ====================
[[test.validator.clone]]
address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"  # Serum DEX Program

[[test.validator.clone]]
address = "8BnEgHoWFysVcuFFX7QztDmzuH8r5ZFvyP3sYwn1XTh6"  # Serum Market

[[test.validator.clone]]
address = "HjhDkGuABhSzqmQ4KAdfEFYCgwAW8nLzqC4i2rNVPyQ2"  # Serum Bids

[[test.validator.clone]]
address = "4sKRiR2gvBRJ6fWe6CXJuhf96uDddCmTmB6wCP29BWAs"  # Serum Asks

# Note: Serum Event Queue and Vault Signer are not cloned as they may not exist or are PDAs

[[test.validator.clone]]
address = "58g347gyj2GpFga4m3Fbta2fMw3749j8Dn8uJ4N4AX9W"  # Serum Base Vault

[[test.validator.clone]]
address = "6A5NHCj1yF6urc9wZNe6Bcjj4LVszQNj5DwAWG97yzMu"  # Serum Quote Vault

# Note: Serum Vault Signer (V3gQJJhHGaRKS7uoeUVhMKzKWqbQ6dKofhPqGBxmg2c) is a PDA
# and doesn't need to be cloned - it will be derived at runtime

# ==================== Additional Raydium Pools (Optional) ====================
# Uncomment these if you need more pools for testing

# [[test.validator.clone]]
# address = "AVs9TA4nWDzfPJE9gGVNJMVhcQy3V9PGazuz33BfG2RA"  # RAY-USDC Pool

# [[test.validator.clone]]
# address = "DVa7Qmb5ct9RCpaU7UTpSaf3GVMYz17vNVU67XpdCRut"  # SOL-USDT Pool
